version: "3.9"
services:
    api:
        image: "clue/json-server:latest"
        ports:
            - "3000:80"
        volumes:
            - ./data/json-server/lumber_futures.json:/data/db.json

    db:
        image: postgres:13.2
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: test
        ports:
            - "5432:5432"
        volumes:
            - ./data/db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:rw
            - ./data/db/hcpcs_codes_2018.csv:/tmp/hcpcs_codes_2018.csv
            - database:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

    spark-master:
        image: bde2020/spark-master:latest
        ports:
            - "8080:8080"
            - "7077:7077"
        environment:
            - INIT_DAEMON_STEP=setup_spark
        volumes:
            - ./data/spark:/tmp/spark

    spark-worker-1:
        image: bde2020/spark-worker:latest
        depends_on:
            - spark-master
        ports:
            - "8081:8081"
        environment:
            - "SPARK_MASTER=spark://spark-master:7077"
        volumes:
            - ./data/spark:/tmp/spark

    spark-worker-2:
        image: bde2020/spark-worker:latest
        depends_on:
            - spark-master
        ports:
            - "8082:8081"
        environment:
            - "SPARK_MASTER=spark://spark-master:7077"
        volumes:
            - ./data/spark:/tmp/spark
    
    elasticsearch:
        image: elasticsearch:7.12.1
        ports: 
            - "9200:9200"
            - "9300:9300"
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data
        environment:
            - "discovery.type=single-node"
            - "xpack.security.enabled=false"
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        ulimits:
            nproc: 3000
            nofile: 65536
            memlock: -1
        deploy:
            resources:
                limits:
                    memory: 2g
    
    kibana:
        image: kibana:7.12.1
        ports:
            - "5601:5601"
        environment:
            - "xpack.security.enabled=false"

volumes:
    database:
    elasticsearch:
